namespace VarBounds {
class Exception {};
void test() {
   try {}
   catch(Exception&) {}
}
}